apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: report-service
        image: financedoc.kr.ncr.ntruss.com/report-service:latest
        ports:
        - containerPort: 8080
      