apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: user-service
        image: financedoc.kr.ncr.ntruss.com/user-service:latest
        ports:
        - containerPort: 8080
      